noDuplicatas   = ['ACURCIO CASTELO DAVID', 'ADEMARIA APARECIDA DE SOUZA', 'ADRIANO CESAR ROSA DA COSTA' ]
withDuplicatas = ['ACURCIO CASTELO DAVID', 'ACURCIO CASTELO DAVID', 'ACURCIO CASTELO DAVID', 'ADEMARIA APARECIDA DE SOUZA', 'ADRIANO CESAR ROSA DA COSTA', 'ADRIANO CESAR ROSA DA COSTA' ]
from collections import defaultdict




    
quantidade_Vezes_Professores()